Added WebRTC building to Github CI.

diff --git a/.github/workflows/win.yml b/.github/workflows/win.yml
--- a/.github/workflows/win.yml
+++ b/.github/workflows/win.yml
@@ -60,6 +60,7 @@ jobs:
       VC: "call vcvars32.bat && cd Libraries"
       GIT: "https://github.com"
       QT: "5_12_8"
+      QT_VER: "5.12.8"
       OPENSSL_VER: "1_1_1"
       UPLOAD_ARTIFACT: "false"
       ONLY_CACHE: "false"
@@ -120,6 +121,20 @@ jobs:
           git clone $GIT/desktop-app/patches.git
           cd Patches
           eval $checkoutCommit
+
+      - name: Find any version of Python 2.
+        shell: cmd
+        run: |
+          echo Find any version of Python 2.
+          for /D %%a in (C:\hostedtoolcache\windows\Python\2.*) do (
+            SET PY2=%%a\x64
+          )
+          if [%PY2%] == [] (
+            echo Python 2 is not found.
+            exit 1
+          )
+          echo Found %PY2%.
+          echo ::set-env name=PY2::%PY2%
 
       - name: LZMA.
         shell: cmd
@@ -214,16 +229,6 @@ jobs:
         run: |
           cd %LibrariesPath%
 
-          echo Find any version of Python 2.
-          for /D %%a in (C:\hostedtoolcache\windows\Python\2.*) do (
-            SET PY2=%%a\x64
-          )
-          IF [%PY2%] == [] (
-            echo Python 2 is not found.
-            exit 1
-          )
-          echo Found %PY2%.
-
           git clone %GIT%/telegramdesktop/gyp.git
           cd gyp
           SET PATH=%PY2%;%cd%;%PATH%
@@ -293,7 +298,7 @@ jobs:
         id: cache-qt
         uses: actions/cache@v2
         with:
-          path: ${{ env.LibrariesPath }}/Qt-5.12.8
+          path: ${{ env.LibrariesPath }}/Qt-${{ env.QT_VER }}
           key: ${{ runner.OS }}-qt-${{ env.CACHE_KEY }}-${{ hashFiles('**/qtbase_5_12_8/*') }}
       - name: Configure Qt 5.12.8.
         if: steps.cache-qt.outputs.cache-hit != 'true'
@@ -304,7 +309,7 @@ jobs:
           git clone git://code.qt.io/qt/qt5.git qt_%QT%
           cd qt_%QT%
           perl init-repository --module-subset=qtbase,qtimageformats
-          git checkout v5.12.8
+          git checkout v%QT_VER%
           git submodule update qtbase
           git submodule update qtimageformats
           cd qtbase
@@ -315,7 +320,7 @@ jobs:
           SET LIBS=libcrypto.lib Ws2_32.lib Gdi32.lib Advapi32.lib Crypt32.lib User32.lib
 
           configure ^
-          -prefix "%LibrariesPath%\Qt-5.12.8" ^
+          -prefix "%LibrariesPath%\Qt-%QT_VER%" ^
           -debug ^
           -force-debug-info ^
           -opensource ^
@@ -341,6 +346,64 @@ jobs:
           jom -j%NUMBER_OF_PROCESSORS% install
 
           cd ..
+          rmdir /S /Q qt_%QT%
+
+      - name: WebRTC cache.
+        id: cache-webrtc
+        uses: actions/cache@v2
+        with:
+          path: ${{ env.LibrariesPath }}/webrtc
+          key: ${{ runner.OS }}-webrtc-2-${{ env.CACHE_KEY }}-${{ hashFiles('**/patches/webrtc/*') }}
+      - name: WebRTC.
+        if: steps.cache-webrtc.outputs.cache-hit != 'true'
+        shell: cmd
+        run: |
+          %VC%
+
+          # Qt libjpeg.
+          mkdir qt_%QT%
+          cd qt_%QT%
+          git clone -b %QT_VER% https://github.com/qt/qtbase
+
+          move qtbase\src\3rdparty\libjpeg ..
+          cd ..
+          dir
+          rmdir /S /Q qt_%QT%
+          mkdir qt_%QT%\qtbase\src\3rdparty\
+          move libjpeg qt_%QT%\qtbase\src\3rdparty\
+
+          # Depot tools.
+          cd %LibrariesPath%
+
+          curl -O https://storage.googleapis.com/chrome-infra/depot_tools.zip
+          7z x depot_tools.zip
+          cd depot_tools
+          SET PATH=%PY2%;%cd%;%PATH%
+          SET DEPOT_TOOLS_WIN_TOOLCHAIN=0
+
+          # WebRTC.
+          cd %LibrariesPath%
+
+          mkdir webrtc
+          cd webrtc
+          copy ..\patches\webrtc\.gclient .gclient
+          git clone https://github.com/open-webrtc-toolkit/owt-deps-webrtc src
+          gclient sync --no-history
+          cd src
+          git apply ..\..\patches\webrtc\src.diff
+          cd build
+          git apply ..\..\..\patches\webrtc\build.diff
+          cd ..\third_party
+          git apply ..\..\..\patches\webrtc\third_party.diff
+          cd libsrtp
+          git apply ..\..\..\..\patches\webrtc\libsrtp.diff
+          cd ..\..
+          ..\..\patches\webrtc\configure.bat
+          ninja -C out/Debug webrtc
+
+          # Cleanup.
+          ..\..\patches\webrtc\cleanup_webrtc.bat
+          cd %LibrariesPath%
           rmdir /S /Q qt_%QT%
 
       - name: Read defines.
